### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by JacobsonMT** [JacobsonMT/ndb#11]
Need a name for NDB...

**Comment by ppavlidis** [comment]
Pavlidis lab variant database

boring, but accurate (no, that's not my final answer, just jotting ideas)

**Comment by ppavlidis** [comment]
vardehar (silly?)
varoom (I sort of like this but it's too googleable)

See also: http://www.humgen.nl/SNP_databases.html  
and http://bioinformatics.ca/links_directory/category/human-genome/databases

**Comment by JacobsonMT** [comment]
Varoom is kind of catchy, sounds like a hipster nightclub or something... 

Varoom: The Variant Room - For when you wanna go where everybody knows... the variants nobody knows.

**Comment by ppavlidis** [comment]
Exactly. It's a room for variants to hang out with their friends.

**Comment by mbelmadani** [comment]
I forgot to post some suggestions I had in a google docs. I like the name/acronym Pavlidis lab variant database/PLVD as it's straightforward and passes the Google test, but if we're still looking for more ideas:

Including the word "var":
-Varbank
-Varbook
-Varket (Variant + market)
-Varkit
-Varlab 
-Varmonize (Variant + Harmonize)
-Varnish (I just like the word varnish)
-Vartisan
-ShareVar (reminds me of sharewares)
-VarShed

Miscellaneous names:
-Cilantro
-NovelDB
-GenMarket
-HarmonizeDB

**Comment by ppavlidis** [comment]
Have we converged on PLVD?

**Comment by mbelmadani** [comment]
I'm good with it, only thing that I can think of that might be an issue is that plvd.com/.net/.org are already registered domains. If that's not an issue then I say we go for it.

**Comment by jleong-ndn** [comment]
Sounds good to me; it is also easy to say (going by saying each letter). Domain-wise, we can (probably want to?) use a subdomain of CHiBi/MSL, or map to a subdirectory of CHiBi/MSL like we do with Gemma.
