### ISSUE TITLE
Inheritance Information

### ISSUE THREAD

**Issue by JacobsonMT** [JacobsonMT/ndb#18]
Need inheritance information (yes/no/unknown) in the variant table. Might involve database work?

**Comment by mbelmadani** [comment]
Done. All specific LoF information has been added (when the raw variant data has a field about inheritance.) Only 340 variants were affected. We could add more if we were to consider labeling them by paper (e.g. if PaperA claims to reports novel _de novo_ mutations, we should list all its variants as "De novo")
