### ISSUE TITLE
Better Ranking List

### ISSUE THREAD

**Issue by JacobsonMT** [JacobsonMT/ndb#20]
Better ranking list (possibly to replace the currents ones).

Consider counting De Novo LOF variant events (See Issue #16)

**Comment by mbelmadani** [comment]
At this time, we only have De novo information (yes/no/unknown) for 340 variants, which isn't that big of a representation over all variants (therefor not very meaningful for ranking).

**Comment by mbelmadani** [comment]
Ranking list has been added.

De Novo Variant Events:	3740
Loss of Function Variant Events:	756

The #1 De novo LoF gene has 13 variants.
