### ISSUE TITLE
Heatmap Symmetry

### ISSUE THREAD

**Issue by JacobsonMT** [JacobsonMT/ndb#22]
The Asymmetry in the heatmap is mostly from Dong having multiple copies of variants, which is obscuring the more interesting case of variants being grouped together in some papers.

The duplicates in Dong is not a very interesting statistic to show, whereas I believe that the grouping/splitting of adjacent variants is more relevant to the about section where we describe the methods of data harmonization and curation.

Solution for the moment is to:

-Remove the asymmetry from the heatmap.
-Add a graphic displaying the grouping/splitting to our data harmonization/curation section.

**Comment by mbelmadani** [comment]
Resolved by removing asymmetry from the heatmap.
