### ISSUE TITLE
Search field dropdown has black background

### ISSUE THREAD

**Issue by ppavlidis** [JacobsonMT/ndb#23]
<img width="544" alt="screen shot 2016-01-18 at 15 48 00" src="https://cloud.githubusercontent.com/assets/206415/12405652/ea6d7948-bdfa-11e5-877d-90afc9b2688f.png">

Macosx, chrome

**Comment by ppavlidis** [comment]
Also tooltips on the table column headers.

**Comment by ppavlidis** [comment]
Related? Variant details popup has a transparent background

<img width="705" alt="screen shot 2016-01-18 at 16 07 12" src="https://cloud.githubusercontent.com/assets/206415/12405959/92b5806c-bdfd-11e5-8b58-1cbd05d0a116.png">

**Comment by JacobsonMT** [comment]
Problem was caused by addition of custom background:
Popups which are being appended to the html body instead of being nested in the document flow (primefaces does this for certain things) are inheriting their background from the incorrect parent.
