### ISSUE TITLE
Paper table cells overflow when url is long.

### ISSUE THREAD

**Issue by mbelmadani** [JacobsonMT/ndb#28]
The O'roak3 paper (ndb/paper.xhtml?paperId=26) has an url that is too long and doesn't break properly.

Can reproduce using Google Chrome but not Firefox.

**Comment by JacobsonMT** [comment]
Needs the following css on the table element:

word-wrap: break-word;
word-break: break-all;
table-layout: fixed;

**Comment by mbelmadani** [comment]
Problem is not fixed, but will not occur anymore because we switched from raw URL to DOI link (which is smaller and doesn't require a line break.)

**Comment by mbelmadani** [comment]
Possibly related bug in the variant table. Seems like the allele change columns are offsetting the rest.

![image](https://cloud.githubusercontent.com/assets/14117454/13482255/a03bea30-e0a0-11e5-8cda-7c654b5656f5.png)

**Comment by mbelmadani** [comment]
Example at : /ndb/variant.xhtml?paperId=7

Problem occurs after scrolling for a bit.

**Comment by mbelmadani** [comment]
Fixed by extending the table load function with header resize.
